# Generated by Django 4.0.5 on 2022-06-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
